name: Check Content Restrictions

on:
  pull_request:
    branches: [main] # hoặc branch bạn muốn bảo vệ

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # cần để so sánh với base

      - name: Validate added files only in _posts/
        run: |
          echo "Checking changed files..."
          errors=0

          git diff --name-status origin/${{ github.base_ref }} | while read status file; do
            case "$status" in
              A*)
                if [[ "$file" != _posts/* ]]; then
                  echo "❌ File mới không nằm trong _posts/: $file"
                  errors=1
                fi
                ;;
              M*|D*)
                echo "❌ Không được sửa hoặc xóa file: $file"
                errors=1
                ;;
              *)
                echo "⚠️ Lệnh không rõ: $status $file"
                errors=1
                ;;
            esac
          done

          if [[ "$errors" -ne 0 ]]; then
            echo "PR không hợp lệ. Chỉ được thêm file mới trong _posts/"
            exit 1
          fi